# -*- coding: utf-8 -*-
"""Prob&Estat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5YMt3ahU_BwJP99Pib6gl39oyDZzva9
"""

import pandas as pd
import numpy as np
import array as arr

"""Lendo os dados"""

# dados = arr.array('i', np.array(input().split(", "), dtype = int))
dados = [1, 1, 2, 3, 4, 5, 2, 6, 2, 1, 5, 7, 6, 2, 9]
dados_np = np.array(dados, dtype = int)

dados_np.sort()
dados = dados_np.tolist()

# print(dados)
# print(len(dados))
# for dado in dados:
#   print(dado, ": ", dados.count(dado))

tabela = pd.DataFrame(columns = ['x', 'f', 'f%', 'fac⭣', 'fac⭡', 'fac%⭣', 'fac%⭡'])

amplitude_total = dados[-1] - dados[0]

first_column = arr.array('i', [])


if(amplitude_total <=10):
  i = 0
  for dado in dados:
    if first_column.count(dado) == 0:
      first_column.append(dado)

  while i<len(first_column):

    tabela.loc[i, 'x'] = first_column[i]
    tabela.loc[i, 'f'] = dados.count(first_column[i])
    tabela.loc[i, 'f%'] = round(((tabela.loc[i, 'f'] / len(dados)) * 100), 1)
    if(i == 0):
      tabela.loc[i, 'fac⭣'] = tabela.loc[i, 'f']
      tabela.loc[i, 'fac⭡'] = tabela['f'].sum()
    else:
      tabela.loc[i, 'fac⭣'] = tabela.loc[i-1, 'fac⭣'] + tabela.loc[i, 'f']
      tabela.loc[i, 'fac⭡'] = tabela.loc[i-1, 'fac⭡'] - tabela.loc[i, 'f']

    tabela.loc[i, 'fac%⭣'] = round(((tabela.loc[i, 'fac⭣'] / tabela['f'].sum()) * 100), 1)
    tabela.loc[i, 'fac%⭡'] = round(((tabela.loc[i, 'fac⭡'] / tabela['f'].sum()) * 100), 1)
    i+=1
  tabela.loc[i, 'x'] = "TOTAL"
  tabela.loc[i, 'f'] = tabela['f'].drop(i).sum()
  tabela.loc[i, 'f%'] = round(((tabela.loc[i, 'f'] / len(dados)) * 100), 1)
  tabela.loc[i, 'fac⭣'] = "-"
  tabela.loc[i, 'fac⭡'] = "-"
  tabela.loc[i, 'fac%⭣'] = "-"
  tabela.loc[i, 'fac%⭡'] = "-"
display(tabela)